### ISSUE TITLE
TODO: User profile pages

### ISSUE THREAD

**Issue by petrspelos** [petrspelos/fpf-rpg#1]
- [x] View your own profile
- [x] View other user's profile
- [x] Pair other's profiles with their avatars in all places
