### ISSUE TITLE
ToDo before release

### ISSUE THREAD

**Issue by petrspelos** [petrspelos/fpf-rpg#3]
These are the tasks we need to finish before shipping the project.
## TASK LIST
- [ ] Profit
- [ ] Konec hry, když zdraví klesne pod 0%
- [ ] Zdravý rozum brání vůči poškození zdraví
- [ ] Algoritmus pro vyhodnocení škola "Questu"
- [ ] Škola funguje jako aréna
- [ ] Neexistují obory, celkově "Jít do školy" je samostatný quest
- [ ] Zakoupení 100% zdraví (za cenu podle Configu)
- [ ] Zakoupení 100% zdravého rozumu (za cenu podle Configu)
- [ ] Friend request
- [ ] Profilové obrázky a jména odkazují na profily uživatelů
- [x] Profilové stránky uživatele
- [x] Práce ubírá zdravý rozum (minimální hodnota 0%, maximální 100%)
- [x] Nejbohatší studenti
- [x] Možnost pracovat
- [x] Herní informace o uživateli
- [x] Migrace na zabezpečený hosting
- [x] Tvorba a správa účtů
- [x] Základní abstrakce databáze
- [x] Základní MVC architektura
